import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@pomofy/ui/global.css'
import { Toaster } from '@pomofy/ui'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Pomofy',
    description: 'Generated by create turbo',
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en">
            <body className={`${inter.className} min-h-screen`}>
                {children}
                <Toaster />
            </body>
        </html>
    )
}
