name: Web Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - 'main'
        paths:
            - 'apps/web/**'

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Download
              uses: actions/checkout@v4
            - name: pnpm setup
              uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Run test
              run: pnpm run test
    Deploy-Production:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: pnpm setup
              uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Run build
              run: pnpm run build:web
            - uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-args: '--prod'
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
                  working-directory: ./apps/web
